language: ruby
rvm:
- ruby-head
- 2.1
- 2.0
- 1.9.3
- 1.9.2
- jruby-head
- jruby-1.7
- rbx
bundler_args: "--without development"
addons:
  code_climate:
    repo_token:
      secure: G3aVZeyCMZutQxsLu+hYHWgR/kqeLyn120obZwZ/17xc/VFx1y1F5f9Cqw/awj/f8+xl+UinOp69AM8w1JAEqD5I4N8L1nLJja+CSrWYUxSBOpGua6CtrEWB1VLyoxdXUNOL1oGQenKXZqQtbHRyUPuxebaP1K1XUHO3X5wnb6k=
